- job:
    name: ceph-ansible-galaxy
    node: small && trusty
    project-type: freestyle
    defaults: global
    display-name: 'ceph-ansible: Update galaxy roles'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-ansible

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - main
          browser: auto
          basedir: "ceph-ansible"
          timeout: 20

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - ssh-agent-credentials:
          # "jenkins-build" SSH key, needed for access to ceph-ansible.git
          users:
            - 'jenkins-build'
