- job:
    name: kernel-trigger
    node: built-in
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: 1
          num-to-keep: 10
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-client
    discard-old-builds: true

    triggers:
      - github

    scm:
    - raw:
        xml: |
          <scm class="hudson.plugins.git.GitSCM">
            <configVersion>2</configVersion>
            <userRemoteConfigs>
              <hudson.plugins.git.UserRemoteConfig>
                <name>origin</name>
                <refspec>+refs/heads/*:refs/remotes/origin/*</refspec>
                <url>https://github.com/ceph/ceph-client.git</url>
              </hudson.plugins.git.UserRemoteConfig>
            </userRemoteConfigs>
            <branches>
              <hudson.plugins.git.BranchSpec>
                <name>origin/testing</name>
              </hudson.plugins.git.BranchSpec>
              <hudson.plugins.git.BranchSpec>
                <name>origin/master</name>
              </hudson.plugins.git.BranchSpec>
              <hudson.plugins.git.BranchSpec>
                <name>origin/for-linus</name>
              </hudson.plugins.git.BranchSpec>
              <hudson.plugins.git.BranchSpec>
                <name>*/wip*</name>
              </hudson.plugins.git.BranchSpec>
              <hudson.plugins.git.BranchSpec>
                <name>origin/ceph-iscsi*</name>
              </hudson.plugins.git.BranchSpec>
            </branches>
            <disableSubmodules>false</disableSubmodules>
            <recursiveSubmodules>false</recursiveSubmodules>
            <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
            <remotePoll>false</remotePoll>
            <gitTool>Default</gitTool>
            <submoduleCfg class="list"/>
            <reference/>
            <gitConfigName/>
            <gitConfigEmail/>
            <extensions>
              <hudson.plugins.git.extensions.impl.CloneOption>
                <shallow>false</shallow>
                <noTags>true</noTags>
                <timeout>120</timeout>
              </hudson.plugins.git.extensions.impl.CloneOption>
              <hudson.plugins.git.extensions.impl.CheckoutOption>
                <timeout>20</timeout>
              </hudson.plugins.git.extensions.impl.CheckoutOption>
              <hudson.plugins.git.extensions.impl.WipeWorkspace/>
            </extensions>
          </scm>

    builders:
      - trigger-builds:
        - project: 'kernel'
          predefined-parameters: |
            BRANCH=${{GIT_BRANCH}}
            FORCE=True
