- scm:
    name: ceph-iscsi
    scm:
      - git:
          url: https://github.com/ceph/ceph-iscsi.git
          branches:
            - $CEPH_ISCSI_BRANCH
          skip-tag: true
          wipe-workspace: true
          basedir: "ceph-iscsi"

- scm:
    name: ceph-iscsi-tools
    scm:
      - git:
          url: https://github.com/ceph/ceph-iscsi-tools.git
          branches:
            - $CEPH_ISCSI_TOOLS_BRANCH
          skip-tag: true
          wipe-workspace: true
          basedir: "ceph-iscsi-tools"

- job:
    name: ceph-iscsi-stable
    project-type: matrix
    defaults: global
    display-name: 'ceph-iscsi-stable'
    concurrent: true

    parameters:
      - string:
          name: CEPH_ISCSI_BRANCH
          description: "The git branch (or tag) to build"
          default: "3.6"

      - string:
          name: CEPH_ISCSI_TOOLS_BRANCH
          description: "The git branch (or tag) to build"
          default: "2.2"

      - string:
          name: DISTROS
          description: "A list of distros to build for. Available options are: centos8 centos9"
          default: "centos8 centos9"

      - string:
          name: ARCHS
          description: "A list of architectures to build for. Available options are: x86_64"
          default: "x86_64"

      - bool:
          name: THROWAWAY
          description: "
Default: False. When True it will not POST binaries to chacra. Artifacts will not be around for long. Useful to test builds."
          default: false

      - bool:
          name: FORCE
          description: "
If this is unchecked, then nothing is built or pushed if they already exist in chacra. This is the default.

If this is checked, then the binaries will be built and pushed to chacra even if they already exist in chacra."
          default: true

      - string:
          name: BUILD_VIRTUALENV
          description: "Base parent path for virtualenv locations, set to avoid issues with extremely long paths that are incompatible with tools like pip. Defaults to '/tmp/' (note the trailing slash, which is required)."
          default: "/tmp/"

    execution-strategy:
       combination-filter: |
         DIST == AVAILABLE_DIST && ARCH == AVAILABLE_ARCH &&
         (ARCH == "x86_64" || (ARCH == "arm64" && ["centos8"].contains(DIST)))
    axes:
      - axis:
          type: label-expression
          name: MACHINE_SIZE
          values:
            - huge
      - axis:
          type: label-expression
          name: AVAILABLE_ARCH
          values:
            - x86_64
      - axis:
          type: label-expression
          name: AVAILABLE_DIST
          values:
            - centos8
            - centos9
      - axis:
          type: dynamic
          name: DIST
          values:
            - DISTROS
      - axis:
          type: dynamic
          name: ARCH
          values:
            - ARCHS

    scm:
      - ceph-iscsi
      - ceph-iscsi-tools

    builders:
      - shell: |
          echo "Cleaning up top-level workarea (shared among workspaces)"
          rm -rf dist
          rm -rf venv
          rm -rf release
      # rpm build scripts
      - shell:
          !include-raw-verbatim:
            - ../../build/validate_rpm
            - ../../../scripts/build_utils.sh
            - ../../build/setup
            - ../../build/build_rpm

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - inject:
                    properties-file: ${{WORKSPACE}}/build_info
                - shell:
                    !include-raw-verbatim:
                      - ../../../scripts/build_utils.sh
                      - ../../build/failure

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: chacractl-key
              variable: CHACRACTL_KEY
      - credentials-binding:
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
