- job:
    name: sync-images
    id: sync-images
    node: small && centos9
    defaults: global
    display-name: sync-images
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    triggers:
      - timed: '@daily'

    parameters:
      - string:
          name: DEST_REGISTRY
          description: "The destination registry hostname. Eg: quay.io"
          default: "quay.io/ceph"

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - username-password-separated:
              credential-id: sync-images-from-docker-to-quay
              username: DEST_USERNAME
              password: DEST_PASSWORD