- job:
    name: ceph-website
    description: This job builds the main branch of https://github.com/ceph/ceph.io and keeps the website up to date
    node: www
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: 20
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph.io

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph.io
          branches:
            - main
          browser: auto
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/ceph-website/install-deps.sh
            - ../../build/build
