- job:
    name: ceph-dev-pipeline-trigger
    project-type: pipeline
    quiet-period: 1
    concurrent: true
    pipeline-scm:
      scm:
        - git:
            url: https://github.com/ceph/ceph-build
            branches:
              - jenkinsfile
            shallow-clone: true
            submodule:
              disable: true
            wipe-workspace: true
      script-path: ceph-dev-pipeline-trigger/build/Jenkinsfile
      lightweight-checkout: true
      do-not-fetch-tags: true

    triggers:
      - generic-webhook-trigger:
          token: ceph-dev-pipeline-trigger
          token-credential-id: pipeline-trigger-token
          print-contrib-var: true
          header-params:
            - key: X_GitHub_Event
              value: ""
          post-content-params:
            - type: JSONPath
              key: head_commit
              value: $.head_commit.message
            - type: JSONPath
              key: ref
              value: $.ref
            - type: JSONPath
              key: pusher
              value: $.pusher.name
          regex-filter-text: $head_commit
          regex-filter-expression: "(?i)CI-PIPELINE: true"
          cause: "Push to $ref by $pusher"
