- job:
    name: ceph-ansible-rpm
    node: 'centos8 && x86_64 && small && !sepia'
    project-type: freestyle
    defaults: global
    disabled: false
    display-name: 'ceph-ansible: RPMs'
    description: 'Build RPMs for every ceph-ansible Git branch'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 1
          num-to-keep: 10
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-ansible
    discard-old-builds: true

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible
          browser: auto
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
          - text:
              credential-id: chacractl-key
              variable: CHACRACTL_KEY
