- job:
    name: "ceph-volume-test"
    description: 'This job will trigger all ceph-volume functional tests given a branch and sha1.'
    project-type: multijob
    defaults: global
    display-name: 'ceph-volume functional test suite'
    block-downstream: false
    block-upstream: false
    concurrent: true
    properties:
      - build-discarder:
          days-to-keep: 20
          artifact-num-to-keep: 20
      - github:
          url: https://github.com/ceph/ceph

    parameters:
      - string:
          name: CEPH_BRANCH
          description: "The ceph branch to test against"
          default: "main"
      - string:
          name: CEPH_SHA1
          description: "The ceph sha1 to test against"
          default: "latest"
      - string:
          name: CEPH_REPO_URL
          description: "The full https url to clone from"
          default: "https://github.com/ceph/ceph.git"

    builders:
      - multijob:
          name: 'testing ceph-volume'
          condition: SUCCESSFUL
          projects:
            - name: ceph-volume-scenario
              current-parameters: true
              predefined-parameters: |
                DISTRO=centos
                OBJECTSTORE=bluestore
                METHOD=lvm
                SCENARIO=unencrypted
            - name: ceph-volume-scenario
              current-parameters: true
              predefined-parameters: |
                DISTRO=centos
                OBJECTSTORE=bluestore
                METHOD=lvm
                SCENARIO=dmcrypt
            - name: ceph-volume-scenario
              current-parameters: true
              predefined-parameters: |
                DISTRO=centos
                OBJECTSTORE=bluestore
                METHOD=raw
                SCENARIO=unencrypted
            - name: ceph-volume-scenario
              current-parameters: true
              predefined-parameters: |
                DISTRO=centos
                OBJECTSTORE=bluestore
                METHOD=raw
                SCENARIO=dmcrypt
