- job:
    name: jenkins-job-builder
    node: small
    project-type: freestyle
    defaults: global
    display-name: 'Jenkins Job Builder'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-build

    parameters:
      - bool:
          name: FORCE
          default: false
          description: "
If this is unchecked, then JJB will use its cache to update jobs. This makes this JJB job run faster, but it could cause JJB to fail to update some Jenkins jobs if the jobs have been changed outside of this JJB job's workflow. (This is the default.)

If this is checked, JJB will wipe out its cache and force each job to align with the configurations in main."

    triggers:
      - github

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - username-password-separated:
              credential-id: jenkins-api-token
              username: JOB_BUILDER_USER
              password: JOB_BUILDER_PASS

    scm:
      - git:
          url: https://github.com/ceph/ceph-build
          branches:
            - main
          browser: auto
          timeout: 20

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - SUCCESS
                  - NOT_BUILT
                  - UNSTABLE
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell: 'rm $HOME/.jenkins_jobs.*.ini'
