
- project:
    name: ceph-volume-cephadm-prs
    distro:
      - centos
    objectstore:
      - bluestore
    method:
      - lvm
      - raw
    scenario:
      - unencrypted
      - dmcrypt

    jobs:
      - 'ceph-volume-prs-{distro}-{objectstore}-{method}-{scenario}'

- job-template:
    name: 'ceph-volume-prs-{distro}-{objectstore}-{method}-{scenario}'
    display-name: 'ceph-volume {method}: Pull Request [{distro}-{objectstore}-{scenario}]'
    node: vagrant&&libvirt&&centos9
    concurrent: true
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph
      - build-discarder:
          days-to-keep: 30
    discard-old-builds: true

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

      # this is injected by the ghprb plugin, and is fully optional but may help in manually triggering
      # a job that can end up updating a PR
      - string:
          name: ghprbSourceBranch
          description: "When manually triggered, and the remote PR isn't a branch in the ceph.git repo This can be specified to determine the actual branch."
      - string:
          name: ghprbTargetBranch
          description: 'Required when manually triggered,  the targeted branch needs to be set (e.g. "luminous" or "main")'
      - string:
          name: GITHUB_SHA
          description: "The tip (last commit) in the PR, a sha1 like 7d787849556788961155534039886aedfcdb2a88 (if set, will report status to Github)"
      - password:
          name: GITHUB_OAUTH_TOKEN
          description: "Secret API Token to set status. Only needed when manually triggering a PR test"


    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          only-trigger-phrase: true
          trigger-phrase: '^jenkins test ceph-volume {distro} {objectstore}-{method}-{scenario}|jenkins test ceph-volume all.*|jenkins test ceph-volume {distro} all.*'
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "ceph-volume {method} testing {distro}-{objectstore}-{scenario}"
          started-status: "ceph-volume {method} running {distro}-{objectstore}-{scenario}"
          success-status: "ceph-volume {method} {distro}-{objectstore}-{scenario} OK"
          failure-status: "ceph-volume {method} {distro}-{objectstore}-{scenario} failed"

    scm:
      - git:
          url: https://github.com/ceph/ceph.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - inject:
          properties-content: |
            DISTRO={distro}
            OBJECTSTORE={objectstore}
            METHOD={method}
            SCENARIO={scenario}
            GITHUB_REPOSITORY="ceph/ceph"
            GITHUB_STATUS_CONTEXT="ceph-volume testing {distro}-{objectstore}-{method}-{scenario}"
            GITHUB_STATUS_STARTED="running"
            GITHUB_STATUS_SUCCESS="OK"
            GITHUB_STATUS_FAILURE="failed"
            GITHUB_STATUS_ERROR="completed with errors"
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-escape:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false
