- scm:
    name: nfs-ganesha
    scm:
      - git:
          url: https://github.com/nfs-ganesha/nfs-ganesha.git
          branches:
            - $NFS_GANESHA_BRANCH
          skip-tag: true
          wipe-workspace: true
          basedir: "nfs-ganesha"

- scm:
    name: nfs-ganesha-debian
    scm:
      - git:
          url: https://github.com/nfs-ganesha/nfs-ganesha-debian.git
          branches:
            - $NFS_GANESHA_DEBIAN_BRANCH
          skip-tag: true
          wipe-workspace: true
          basedir: "nfs-ganesha-debian"
- job:
    name: nfs-ganesha
    project-type: matrix
    defaults: global
    display-name: 'nfs-ganesha'
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/nfs-ganesha/nfs-ganesha
      - build-discarder:
          days-to-keep: 90
          artifact-days-to-keep: 90

    concurrent: true
    parameters:
      - string:
          name: NFS_GANESHA_BRANCH
          description: "The git branch (or tag) to build"
          default: "V5.7"

      - string:
          name: NFS_GANESHA_DEBIAN_BRANCH
          description: "The git branch (or tag) for debian build scripts for nfs-ganesha"
          default: "xenial-nfs-ganesha-shaman"

      - string:
          name: CEPH_BRANCH
          description: "The branch of Ceph to get the repo file of for libcephfs"
          default: main

      - string:
          name: DISTROS
          description: "A list of distros to build for. Available options are: bionic"
          default: "bionic"

      - string:
          name: ARCHS
          description: "A list of architectures to build for. Available options are: x86_64 and arm64"
          default: "x86_64 arm64"

      - bool:
          name: THROWAWAY
          description: "
Default: False. When True it will not POST binaries to chacra. Artifacts will not be around for long. Useful to test builds."
          default: false

      - bool:
          name: FORCE
          description: "
If this is unchecked, then nothing is built or pushed if they already exist in chacra. This is the default.

If this is checked, then the binaries will be built and pushed to chacra even if they already exist in chacra."

      - string:
          name: BUILD_VIRTUALENV
          description: "Base parent path for virtualenv locations, set to avoid issues with extremely long paths that are incompatible with tools like pip. Defaults to '/tmp/' (note the trailing slash, which is required)."
          default: "/tmp/"

    execution-strategy:
       combination-filter: DIST==AVAILABLE_DIST && ARCH==AVAILABLE_ARCH && (ARCH=="x86_64" || (ARCH == "arm64" && DIST == "centos8"))
    axes:
      - axis:
          type: label-expression
          name: MACHINE_SIZE
          values:
            - huge
      - axis:
          type: label-expression
          name: AVAILABLE_ARCH
          values:
            - x86_64
            - arm64
      - axis:
          type: label-expression
          name: AVAILABLE_DIST
          values:
            - focal
      - axis:
          type: dynamic
          name: DIST
          values:
            - DISTROS
      - axis:
          type: dynamic
          name: ARCH
          values:
            - ARCHS
    triggers:
      - github
      - timed: "0 1,13 * * *"

    scm:
      - nfs-ganesha
      - nfs-ganesha-debian

    builders:
      - shell: |
          echo "Cleaning up top-level workarea (shared among workspaces)"
          rm -rf dist
          rm -rf venv
          rm -rf release
      # debian build scripts
      - shell:
          !include-raw-verbatim:
            - ../../build/validate_deb
            - ../../../scripts/build_utils.sh
            - ../../build/setup
            - ../../build/build_deb
      # rpm build scripts
      - shell:
          !include-raw-verbatim:
            - ../../build/validate_rpm
            - ../../../scripts/build_utils.sh
            - ../../build/setup
            - ../../build/build_rpm
      - shell: if [ -f /etc/yum.repos.d/shaman.repo ]; then sudo rm -f /etc/yum.repos.d/shaman.repo; fi

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - inject:
                    properties-file: ${{WORKSPACE}}/build_info

                - shell:
                    !include-raw-verbatim:
                      - ../../../scripts/build_utils.sh
                      - ../../build/failure
                - shell: if [ -f /etc/yum.repos.d/shaman.repo ]; then sudo rm -f /etc/yum.repos.d/shaman.repo; fi

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: chacractl-key
              variable: CHACRACTL_KEY
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
