- job:
    name: ceph-cbt-lint
    display-name: 'ceph-cbt: lint tests'
    node: python3
    project-type: freestyle
    defaults: global
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false

    properties:
      - github:
          url: https://github.com/ceph/cbt/
      - build-discarder:
          days-to-keep: 7
          num-to-keep: 30
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
    discard-old-builds: true

    parameters:
      - string:
          name: ghprbPullId
          description: "the GitHub pull id, like '72' in 'cbt/pull/72'"

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          cancel-builds-on-update: true
          only-trigger-phrase: false
          trigger-phrase: 'jenkins test cbt lint'
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "ceph-cbt tox testing"
          started-status: "ceph-cbt tox running"
          success-status: "ceph-cbt tox OK"
          failure-status: "ceph-cbt tox failed"

    scm:
      - git:
          url: https://github.com/ceph/cbt
          branches:
            - origin/pr/${{ghprbPullId}}/merge
          refspec: +refs/pull/${{ghprbPullId}}/*:refs/remotes/origin/pr/${{ghprbPullId}}/*
          timeout: 20
          shallow-clone: true
          wipe-workspace: true

    builders:
      - shell: |
          virtualenv -q --python python3 venv
          . venv/bin/activate
          pip install tox
          pip install git+https://github.com/ceph/githubcheck.git
          sha1=$(git rev-parse refs/remotes/origin/pr/${{ghprbPullId}}/head)
          tox -e pep8 | github-check   \
            --lint                        \
            --lint-tox-dir=.              \
            --lint-preamble=pep8:flake8   \
            --owner "ceph"                               \
            --repo "cbt"                                 \
            --pkey-file $GITHUB_CHECK_PKEY_PEM           \
            --app-id "62865"                             \
            --install-id "8465036"                       \
            --name "cbt-lint"                            \
            --sha $sha1                                  \
            --external-id $BUILD_ID                      \
            --details-url $BUILD_URL                     \
            --title cbt-lint

    wrappers:
      - credentials-binding:
          - file:
              credential-id: cephacheck.2020-04-29.private-key.pem
              variable: GITHUB_CHECK_PKEY_PEM
