- job:
    name: ceph-release-rpm
    project-type: matrix
    defaults: global
    description: Builds the repository configuration package for ceph-release.  RPMS Only
    block-downstream: false
    block-upstream: false

    parameters:
      - string:
          name: RELEASE
          default: pacific

      - bool:
          name: TEST
          description: "
If this is unchecked, then the builds will be pushed to chacra with the correct ref. This is the default.

If this is checked, then the builds will be pushed to chacra under the 'test' ref."

      - bool:
          name: FORCE
          description: "
If this is unchecked, then then nothing is built or pushed if they already exist in chacra. This is the default.

If this is checked, then the binaries will be built and pushed to chacra even if they already exist in chacra."

    axes:
      - axis:
          type: label-expression
          name: ARCH
          values:
            - x86_64

      - axis:
          type: label-expression
          name: DIST
          values:
            - centos7
            - centos8
            - centos9

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: chacractl-key
              variable: CHACRACTL_KEY
