- job:
    name: ceph-setup
    description: "This job:\r\n- Creates the version commit\r\n- Checks out the branch and builds the tarballs, diffs, and dsc that are passed to the ceph-build step.\r\n\r\nNotes:\r\nJob needs to run on a releatively recent debian system.  The Restrict where run feature is used to specifiy an appropriate label.\r\nThe clear workspace before checkout box for the git plugin is used."
    node: huge && bionic && !arm64
    display-name: 'ceph-setup'
    block-downstream: false
    block-upstream: false
    concurrent: true
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: 25
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph
      - copyartifact:
          projects: ceph-build,ceph-tag,ceph

    parameters:
      - string:
          name: BRANCH
          description: "The git branch (or tag) to build (e.g., pacific) DO NOT INCLUDE '-release'"

    scm:
      - git:
          url: https://github.com/ceph/ceph-build.git
          credentials-id: 'jenkins-build'
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true
          basedir: "ceph-build"
          branches:
            - origin/main

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/create_tag
            - ../../build/build
    publishers:
      - archive:
          artifacts: 'ceph-build/ansible/ceph/dist/**'
          allow-empty: false
          latest-only: false

      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-verbatim:
                      - ../../../scripts/build_utils.sh
                      - ../../build/failure

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
      - ssh-agent-credentials:
          # "jenkins-build" SSH key, needed so we can push/pull to/from private repos
          user: 'jenkins-build'
