- job:
    name: ceph-devstack
    description: Run ceph-devstack
    project-type: pipeline
    concurrent: false
    pipeline-scm:
      scm:
        - git:
            url: https://github.com/zmc/ceph-devstack
            branches:
              - origin/${{CEPH_DEVSTACK_BRANCH}}
    parameters:
      - string:
          name: CEPH_DEVSTACK_BRANCH
          default: "main"
      - string:
          name: TEUTHOLOGY_BRANCH
          default: "main"
      - string:
          name: TEUTHOLOGY_CEPH_BRANCH
          default: "main"
      - string:
          name: TEUTHOLOGY_CEPH_REPO
          default: "https://github.com/ceph/ceph.git"
      - string:
          name: TEUTHOLOGY_SUITE
          default: "teuthology:no-ceph"
      - string:
          name: TEUTHOLOGY_SUITE_BRANCH
          default: "main"
      - string:
          name: TEUTHOLOGY_SUITE_REPO
          default: "https://github.com/ceph/ceph.git"

    triggers:
      - github-pull-request:
          admin-list:
            - zmc
            - dmick
            - kamoltat
            - amathuria
          org-list:
            - ceph
          trigger-phrase: 'jenkins test.*|jenkins retest.*'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false
